version: '3'
services:
  mongo-express:
    image: mongo-express
    container_name: 'mongo-express'
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: mongo2020
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo2020
    links:
      - mongo
  mongo:
    image: mongo
    container_name: 'mongo'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo2020
    ports:
      - "27017:27017"
    volumes:
      - /home/paulo/projetos/node-projects/MongoDB:/data/db
